# Lua CI workflow: runs linting, testing, and coverage for Lua projects using LuaRocks

name: Lua CI

on:
  workflow_call:
    inputs:
      lua-version:
        description: 'Lua version to use (e.g., 5.1.5, 5.2.4, luajit-2.1.0-beta3)'
        required: false
        default: '5.1.5'
        type: string

jobs:
  lua-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ inputs.lua-version }}

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies
        run: |
          luarocks install --tree=lua_modules --deps-only *.rockspec

      - name: Install test and coverage tools
        run: |
          luarocks install --tree=lua_modules busted
          luarocks install --tree=lua_modules luacov
          luarocks install --tree=lua_modules luacheck

      - name: Override luacheck std for current Lua version
        run: |
          case "${{ inputs.lua-version }}" in
            5.1*|luajit*) STD="lua51" ;;
            5.2*) STD="lua52" ;;
            5.3*) STD="lua53" ;;
            5.4*) STD="lua54" ;;
            *) STD="lua51" ;;
          esac
          echo "std = \"$STD\"" >> .luacheckrc
          echo "Using luacheck std: $STD"

      - name: Lint code with luacheck
        run: ./lua_modules/bin/luacheck .

      - name: Run tests with coverage
        run: ./lua_modules/bin/busted --coverage .

      - name: Generate coverage report
        run: ./lua_modules/bin/luacov

      - name: Show coverage report
        run: cat luacov.report.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: luacov.report.out
          path: luacov.report.out
